apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: cuda-demo
spec:
  components:
    - name: cuda-edge
      type: edgefarm-applications
      properties:
        image: ci4rail/dev-cuda-demo:v1
        nodepoolSelector:
          matchLabels:
            cuda-demo: ""
        name: cuda-edge
        
        cpu: 0.25
        memory: 256Mi
        
        
